// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGvgnvQrjBK4YYv48Le9HKI0LbEAKPFm4',
    appId: '1:898335008605:web:8e85f221a9ecc10957eab4',
    messagingSenderId: '898335008605',
    projectId: 'fir-1-3f57a',
    authDomain: 'fir-1-3f57a.firebaseapp.com',
    storageBucket: 'fir-1-3f57a.firebasestorage.app',
    measurementId: 'G-0P9QZFKSZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCthfLxwrzkK6lfXHXI9mMPbUj3dl3N8N8',
    appId: '1:898335008605:android:c40126664559a35157eab4',
    messagingSenderId: '898335008605',
    projectId: 'fir-1-3f57a',
    storageBucket: 'fir-1-3f57a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu3CTY6nA6ZoQUCrC_89pjOwDK4RMbybs',
    appId: '1:898335008605:ios:fdcdecbefe37538f57eab4',
    messagingSenderId: '898335008605',
    projectId: 'fir-1-3f57a',
    storageBucket: 'fir-1-3f57a.firebasestorage.app',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu3CTY6nA6ZoQUCrC_89pjOwDK4RMbybs',
    appId: '1:898335008605:ios:fdcdecbefe37538f57eab4',
    messagingSenderId: '898335008605',
    projectId: 'fir-1-3f57a',
    storageBucket: 'fir-1-3f57a.firebasestorage.app',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGvgnvQrjBK4YYv48Le9HKI0LbEAKPFm4',
    appId: '1:898335008605:web:df8dffbb062c423b57eab4',
    messagingSenderId: '898335008605',
    projectId: 'fir-1-3f57a',
    authDomain: 'fir-1-3f57a.firebaseapp.com',
    storageBucket: 'fir-1-3f57a.firebasestorage.app',
    measurementId: 'G-YM87JE26KB',
  );
}
